# Generated by Django 3.1.3 on 2020-12-15 12:38

import sys
sys.path.append('/home/spencer/prod/genrefi/scratch/genre_scrape/py_data')

from django.db import migrations, transaction
from sub_keys import genres

## Notes: Foreign Keys have to referenc a model instance
## get that by filtering for the value that SHOULD be the foreign key
def preload_genre_data(apps, schema_editor):
    Genres = apps.get_model('figenre', 'Genres')
    SubGenres = apps.get_model('figenre', 'SubGenres')

    umb_genres = set(genres.values())
    for i in umb_genres:
        Genres.objects.create(genre=i)
    for sub, umb in genres.items():
        gen_object = Genres.objects.get(genre=umb)
        SubGenres.objects.create(subgenre=sub, genre=gen_object)


class Migration(migrations.Migration):
    dependencies = [
        ('figenre', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(preload_genre_data),
    ]
